package com.lion.controllerability.moneyRecord.data;

import com.lion.controllerability.accountBase.data.Accountbase;
import com.lion.controllerability.accountCustomer.data.Accountcustomer;
import com.lion.controllerability.basisposition.data.Basisposition;
import com.lion.controllerability.customer.data.Customerbase;

import java.util.Date;

public class Moneyrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.RecordId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private Long recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.AccountId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.PositionId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private Long positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.ChangeAmount
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private Long changeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.AfterAmount
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private Long afteramount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.RecordTime
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.Remark
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MoneyRecord.BillNo
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    private String billno;

    private Accountcustomer accountcustomer ;

    public Accountcustomer getAccountcustomer() {
        return accountcustomer;
    }

    public void setAccountcustomer(Accountcustomer accountcustomer) {
        this.accountcustomer = accountcustomer;
    }

    private Customerbase customerbase ;

    public Customerbase getCustomerbase() {
        return customerbase;
    }

    public void setCustomerbase(Customerbase customerbase) {
        this.customerbase = customerbase;
    }

    private Accountbase accountbase ;

    public Accountbase getAccountbase() {
        return accountbase;
    }

    public void setAccountbase(Accountbase accountbase) {
        this.accountbase = accountbase;
    }

    private Basisposition basisposition;

    public Basisposition getBasisposition() {
        return basisposition;
    }

    public void setBasisposition(Basisposition basisposition) {
        this.basisposition = basisposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.RecordId
     *
     * @return the value of MoneyRecord.RecordId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public Long getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.RecordId
     *
     * @param recordid the value for MoneyRecord.RecordId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setRecordid(Long recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.AccountId
     *
     * @return the value of MoneyRecord.AccountId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.AccountId
     *
     * @param accountid the value for MoneyRecord.AccountId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.PositionId
     *
     * @return the value of MoneyRecord.PositionId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public Long getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.PositionId
     *
     * @param positionid the value for MoneyRecord.PositionId
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setPositionid(Long positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.ChangeAmount
     *
     * @return the value of MoneyRecord.ChangeAmount
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public Long getChangeamount() {
        return changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.ChangeAmount
     *
     * @param changeamount the value for MoneyRecord.ChangeAmount
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setChangeamount(Long changeamount) {
        this.changeamount = changeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.AfterAmount
     *
     * @return the value of MoneyRecord.AfterAmount
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public Long getAfteramount() {
        return afteramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.AfterAmount
     *
     * @param afteramount the value for MoneyRecord.AfterAmount
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setAfteramount(Long afteramount) {
        this.afteramount = afteramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.RecordTime
     *
     * @return the value of MoneyRecord.RecordTime
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public Date getRecordtime() {
        return recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.RecordTime
     *
     * @param recordtime the value for MoneyRecord.RecordTime
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setRecordtime(Date recordtime) {
        this.recordtime = recordtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.Remark
     *
     * @return the value of MoneyRecord.Remark
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.Remark
     *
     * @param remark the value for MoneyRecord.Remark
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MoneyRecord.BillNo
     *
     * @return the value of MoneyRecord.BillNo
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MoneyRecord.BillNo
     *
     * @param billno the value for MoneyRecord.BillNo
     *
     * @mbggenerated Tue Mar 10 18:21:56 CST 2020
     */
    public void setBillno(String billno) {
        this.billno = billno == null ? null : billno.trim();
    }
}