package com.lion.controllerability.feeBase.mapper;

import com.lion.controllerability.feeBase.data.Feebase;
import com.lion.controllerability.feeBase.data.FeebaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeebaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int countByExample(FeebaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int deleteByExample(FeebaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int deleteByPrimaryKey(Long feeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int insert(Feebase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int insertSelective(Feebase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    List<Feebase> selectByExample(FeebaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    Feebase selectByPrimaryKey(Long feeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") Feebase record, @Param("example") FeebaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int updateByExample(@Param("record") Feebase record, @Param("example") FeebaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int updateByPrimaryKeySelective(Feebase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FeeBase
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    int updateByPrimaryKey(Feebase record);
}