package com.lion.controllerability.accountBill.mapper;

import com.lion.controllerability.accountBill.data.Accountbill;
import com.lion.controllerability.accountBill.data.AccountbillExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AccountbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int countByExample(AccountbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int deleteByExample(AccountbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int deleteByPrimaryKey(Long recordid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int insert(Accountbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int insertSelective(Accountbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    List<Accountbill> selectByExample(AccountbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    Accountbill selectByPrimaryKey(Long recordid);
    List<Accountbill> selectChargeByCustomerId(@Param("customerld") Long customerId , @Param("yearmonth") String yearMonth);
    List<Accountbill> selectAllCharge(@Param("customerld") Long customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") Accountbill record, @Param("example") AccountbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int updateByExample(@Param("record") Accountbill record, @Param("example") AccountbillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int updateByPrimaryKeySelective(Accountbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    int updateByPrimaryKey(Accountbill record);
}