package com.lion.controllerability.accountCustomer.mapper;

import com.lion.controllerability.accountCustomer.data.Accountcustomer;
import com.lion.controllerability.accountCustomer.data.AccountcustomerExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AccountcustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int countByExample(AccountcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int deleteByExample(AccountcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int insert(Accountcustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int insertSelective(Accountcustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    List<Accountcustomer> selectByExample(AccountcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    Accountcustomer selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int updateByExampleSelective(@Param("record") Accountcustomer record, @Param("example") AccountcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int updateByExample(@Param("record") Accountcustomer record, @Param("example") AccountcustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int updateByPrimaryKeySelective(Accountcustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountCustomer
     *
     * @mbggenerated Tue Mar 03 20:40:12 CST 2020
     */
    int updateByPrimaryKey(Accountcustomer record);
}