package com.lion.controllerability.accountBase.data;

import com.lion.controllerability.accountCustomer.data.Accountcustomer;

import java.util.Date;

public class Accountbase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.AccountId
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.PositionId
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Long positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.PositionTypeFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Byte positiontypeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.AccountNo
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private String accountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.UserTypeFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Byte usertypeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.CreateTime
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.ActiveFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Byte activeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.LeftMoney
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private Long leftmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBase.AccountTypeCode
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    private String accounttypecode;

    private Accountcustomer accountcustomer ;

    public Accountcustomer getAccountcustomer() {
        return accountcustomer;
    }

    public void setAccountcustomer(Accountcustomer accountcustomer) {
        this.accountcustomer = accountcustomer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.AccountId
     *
     * @return the value of AccountBase.AccountId
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.AccountId
     *
     * @param accountid the value for AccountBase.AccountId
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.PositionId
     *
     * @return the value of AccountBase.PositionId
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Long getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.PositionId
     *
     * @param positionid the value for AccountBase.PositionId
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setPositionid(Long positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.PositionTypeFlag
     *
     * @return the value of AccountBase.PositionTypeFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Byte getPositiontypeflag() {
        return positiontypeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.PositionTypeFlag
     *
     * @param positiontypeflag the value for AccountBase.PositionTypeFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setPositiontypeflag(Byte positiontypeflag) {
        this.positiontypeflag = positiontypeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.AccountNo
     *
     * @return the value of AccountBase.AccountNo
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public String getAccountno() {
        return accountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.AccountNo
     *
     * @param accountno the value for AccountBase.AccountNo
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setAccountno(String accountno) {
        this.accountno = accountno == null ? null : accountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.UserTypeFlag
     *
     * @return the value of AccountBase.UserTypeFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Byte getUsertypeflag() {
        return usertypeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.UserTypeFlag
     *
     * @param usertypeflag the value for AccountBase.UserTypeFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setUsertypeflag(Byte usertypeflag) {
        this.usertypeflag = usertypeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.CreateTime
     *
     * @return the value of AccountBase.CreateTime
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.CreateTime
     *
     * @param createtime the value for AccountBase.CreateTime
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.ActiveFlag
     *
     * @return the value of AccountBase.ActiveFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Byte getActiveflag() {
        return activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.ActiveFlag
     *
     * @param activeflag the value for AccountBase.ActiveFlag
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setActiveflag(Byte activeflag) {
        this.activeflag = activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.LeftMoney
     *
     * @return the value of AccountBase.LeftMoney
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public Long getLeftmoney() {
        return leftmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.LeftMoney
     *
     * @param leftmoney the value for AccountBase.LeftMoney
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setLeftmoney(Long leftmoney) {
        this.leftmoney = leftmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBase.AccountTypeCode
     *
     * @return the value of AccountBase.AccountTypeCode
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public String getAccounttypecode() {
        return accounttypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBase.AccountTypeCode
     *
     * @param accounttypecode the value for AccountBase.AccountTypeCode
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    public void setAccounttypecode(String accounttypecode) {
        this.accounttypecode = accounttypecode == null ? null : accounttypecode.trim();
    }
}