package com.lion.controllerability.feeBase.data;

import java.util.Date;

public class Feebase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.FeeId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Long feeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.MerchantNo
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private String merchantno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.MeterId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Long meterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.AccountId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.FeeName
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private String feename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.FeeAmount
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Long feeamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.StatusFlag
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Byte statusflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.TypeFlag
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Byte typeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.PayAccount
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private String payaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.PayTime
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FeeBase.TransNo
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    private String transno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.FeeId
     *
     * @return the value of FeeBase.FeeId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Long getFeeid() {
        return feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.FeeId
     *
     * @param feeid the value for FeeBase.FeeId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setFeeid(Long feeid) {
        this.feeid = feeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.MerchantNo
     *
     * @return the value of FeeBase.MerchantNo
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public String getMerchantno() {
        return merchantno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.MerchantNo
     *
     * @param merchantno the value for FeeBase.MerchantNo
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setMerchantno(String merchantno) {
        this.merchantno = merchantno == null ? null : merchantno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.MeterId
     *
     * @return the value of FeeBase.MeterId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Long getMeterid() {
        return meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.MeterId
     *
     * @param meterid the value for FeeBase.MeterId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setMeterid(Long meterid) {
        this.meterid = meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.AccountId
     *
     * @return the value of FeeBase.AccountId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.AccountId
     *
     * @param accountid the value for FeeBase.AccountId
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.FeeName
     *
     * @return the value of FeeBase.FeeName
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public String getFeename() {
        return feename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.FeeName
     *
     * @param feename the value for FeeBase.FeeName
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setFeename(String feename) {
        this.feename = feename == null ? null : feename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.FeeAmount
     *
     * @return the value of FeeBase.FeeAmount
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Long getFeeamount() {
        return feeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.FeeAmount
     *
     * @param feeamount the value for FeeBase.FeeAmount
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setFeeamount(Long feeamount) {
        this.feeamount = feeamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.StatusFlag
     *
     * @return the value of FeeBase.StatusFlag
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Byte getStatusflag() {
        return statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.StatusFlag
     *
     * @param statusflag the value for FeeBase.StatusFlag
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setStatusflag(Byte statusflag) {
        this.statusflag = statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.TypeFlag
     *
     * @return the value of FeeBase.TypeFlag
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Byte getTypeflag() {
        return typeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.TypeFlag
     *
     * @param typeflag the value for FeeBase.TypeFlag
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setTypeflag(Byte typeflag) {
        this.typeflag = typeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.PayAccount
     *
     * @return the value of FeeBase.PayAccount
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public String getPayaccount() {
        return payaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.PayAccount
     *
     * @param payaccount the value for FeeBase.PayAccount
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setPayaccount(String payaccount) {
        this.payaccount = payaccount == null ? null : payaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.PayTime
     *
     * @return the value of FeeBase.PayTime
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.PayTime
     *
     * @param paytime the value for FeeBase.PayTime
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FeeBase.TransNo
     *
     * @return the value of FeeBase.TransNo
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public String getTransno() {
        return transno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FeeBase.TransNo
     *
     * @param transno the value for FeeBase.TransNo
     *
     * @mbggenerated Wed Mar 18 12:33:09 CST 2020
     */
    public void setTransno(String transno) {
        this.transno = transno == null ? null : transno.trim();
    }
}