package com.lion.controllerability.accountBill.data;

import com.lion.controllerability.accountBase.data.Accountbase;
import com.lion.controllerability.accountCustomer.data.Accountcustomer;
import com.lion.controllerability.basisposition.data.Basisposition;
import com.lion.controllerability.customer.data.Customerbase;

import java.util.Date;

public class Accountbill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.RecordId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.AccountId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.PositionId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.BeginVolume
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Double beginvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.EndVolume
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Double endvolume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.BillAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long billamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.YearMonth
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private String yearmonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.SettlementDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Date settlementdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.BeginDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Date begindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.EndDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.StatusFlag
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long statusflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.OverdueAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long overdueamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.ShouldAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long shouldamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.PayTime
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Date paytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.ActualAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long actualamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.WaterAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long wateramount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.SewageAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long sewageamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.LastPayCostDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Date lastpaycostdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountBill.OtherAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    private Long otheramount;

    private Customerbase customerbase ;

    private Accountcustomer accountcustomer;

    private Accountbase accountbase ;

    private Basisposition basisposition;

    public Basisposition getBasisposition() {
        return basisposition;
    }

    public void setBasisposition(Basisposition basisposition) {
        this.basisposition = basisposition;
    }

    public Customerbase getCustomerbase() {
        return customerbase;
    }

    public void setCustomerbase(Customerbase customerbase) {
        this.customerbase = customerbase;
    }

    public Accountcustomer getAccountcustomer() {
        return accountcustomer;
    }

    public void setAccountcustomer(Accountcustomer accountcustomer) {
        this.accountcustomer = accountcustomer;
    }

    public Accountbase getAccountbase() {
        return accountbase;
    }

    public void setAccountbase(Accountbase accountbase) {
        this.accountbase = accountbase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.RecordId
     *
     * @return the value of AccountBill.RecordId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.RecordId
     *
     * @param recordid the value for AccountBill.RecordId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setRecordid(Long recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.AccountId
     *
     * @return the value of AccountBill.AccountId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.AccountId
     *
     * @param accountid the value for AccountBill.AccountId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.PositionId
     *
     * @return the value of AccountBill.PositionId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.PositionId
     *
     * @param positionid the value for AccountBill.PositionId
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setPositionid(Long positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.BeginVolume
     *
     * @return the value of AccountBill.BeginVolume
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Double getBeginvolume() {
        return beginvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.BeginVolume
     *
     * @param beginvolume the value for AccountBill.BeginVolume
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setBeginvolume(Double beginvolume) {
        this.beginvolume = beginvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.EndVolume
     *
     * @return the value of AccountBill.EndVolume
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Double getEndvolume() {
        return endvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.EndVolume
     *
     * @param endvolume the value for AccountBill.EndVolume
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setEndvolume(Double endvolume) {
        this.endvolume = endvolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.BillAmount
     *
     * @return the value of AccountBill.BillAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getBillamount() {
        return billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.BillAmount
     *
     * @param billamount the value for AccountBill.BillAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setBillamount(Long billamount) {
        this.billamount = billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.YearMonth
     *
     * @return the value of AccountBill.YearMonth
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public String getYearmonth() {
        return yearmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.YearMonth
     *
     * @param yearmonth the value for AccountBill.YearMonth
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setYearmonth(String yearmonth) {
        this.yearmonth = yearmonth == null ? null : yearmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.SettlementDate
     *
     * @return the value of AccountBill.SettlementDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Date getSettlementdate() {
        return settlementdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.SettlementDate
     *
     * @param settlementdate the value for AccountBill.SettlementDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setSettlementdate(Date settlementdate) {
        this.settlementdate = settlementdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.BeginDate
     *
     * @return the value of AccountBill.BeginDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.BeginDate
     *
     * @param begindate the value for AccountBill.BeginDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.EndDate
     *
     * @return the value of AccountBill.EndDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.EndDate
     *
     * @param enddate the value for AccountBill.EndDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.StatusFlag
     *
     * @return the value of AccountBill.StatusFlag
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getStatusflag() {
        return statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.StatusFlag
     *
     * @param statusflag the value for AccountBill.StatusFlag
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setStatusflag(Long statusflag) {
        this.statusflag = statusflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.OverdueAmount
     *
     * @return the value of AccountBill.OverdueAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getOverdueamount() {
        return overdueamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.OverdueAmount
     *
     * @param overdueamount the value for AccountBill.OverdueAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setOverdueamount(Long overdueamount) {
        this.overdueamount = overdueamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.ShouldAmount
     *
     * @return the value of AccountBill.ShouldAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getShouldamount() {
        return shouldamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.ShouldAmount
     *
     * @param shouldamount the value for AccountBill.ShouldAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setShouldamount(Long shouldamount) {
        this.shouldamount = shouldamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.PayTime
     *
     * @return the value of AccountBill.PayTime
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.PayTime
     *
     * @param paytime the value for AccountBill.PayTime
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.ActualAmount
     *
     * @return the value of AccountBill.ActualAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getActualamount() {
        return actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.ActualAmount
     *
     * @param actualamount the value for AccountBill.ActualAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setActualamount(Long actualamount) {
        this.actualamount = actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.WaterAmount
     *
     * @return the value of AccountBill.WaterAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getWateramount() {
        return wateramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.WaterAmount
     *
     * @param wateramount the value for AccountBill.WaterAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setWateramount(Long wateramount) {
        this.wateramount = wateramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.SewageAmount
     *
     * @return the value of AccountBill.SewageAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getSewageamount() {
        return sewageamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.SewageAmount
     *
     * @param sewageamount the value for AccountBill.SewageAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setSewageamount(Long sewageamount) {
        this.sewageamount = sewageamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.LastPayCostDate
     *
     * @return the value of AccountBill.LastPayCostDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Date getLastpaycostdate() {
        return lastpaycostdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.LastPayCostDate
     *
     * @param lastpaycostdate the value for AccountBill.LastPayCostDate
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setLastpaycostdate(Date lastpaycostdate) {
        this.lastpaycostdate = lastpaycostdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountBill.OtherAmount
     *
     * @return the value of AccountBill.OtherAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Long getOtheramount() {
        return otheramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountBill.OtherAmount
     *
     * @param otheramount the value for AccountBill.OtherAmount
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setOtheramount(Long otheramount) {
        this.otheramount = otheramount;
    }
}