package com.lion.controllerability.accountBill.data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AccountbillExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public AccountbillExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordidIsNull() {
            addCriterion("RecordId is null");
            return (Criteria) this;
        }

        public Criteria andRecordidIsNotNull() {
            addCriterion("RecordId is not null");
            return (Criteria) this;
        }

        public Criteria andRecordidEqualTo(Long value) {
            addCriterion("RecordId =", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotEqualTo(Long value) {
            addCriterion("RecordId <>", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidGreaterThan(Long value) {
            addCriterion("RecordId >", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidGreaterThanOrEqualTo(Long value) {
            addCriterion("RecordId >=", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLessThan(Long value) {
            addCriterion("RecordId <", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidLessThanOrEqualTo(Long value) {
            addCriterion("RecordId <=", value, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidIn(List<Long> values) {
            addCriterion("RecordId in", values, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotIn(List<Long> values) {
            addCriterion("RecordId not in", values, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidBetween(Long value1, Long value2) {
            addCriterion("RecordId between", value1, value2, "recordid");
            return (Criteria) this;
        }

        public Criteria andRecordidNotBetween(Long value1, Long value2) {
            addCriterion("RecordId not between", value1, value2, "recordid");
            return (Criteria) this;
        }

        public Criteria andAccountidIsNull() {
            addCriterion("AccountId is null");
            return (Criteria) this;
        }

        public Criteria andAccountidIsNotNull() {
            addCriterion("AccountId is not null");
            return (Criteria) this;
        }

        public Criteria andAccountidEqualTo(Long value) {
            addCriterion("AccountId =", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotEqualTo(Long value) {
            addCriterion("AccountId <>", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidGreaterThan(Long value) {
            addCriterion("AccountId >", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidGreaterThanOrEqualTo(Long value) {
            addCriterion("AccountId >=", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLessThan(Long value) {
            addCriterion("AccountId <", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLessThanOrEqualTo(Long value) {
            addCriterion("AccountId <=", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidIn(List<Long> values) {
            addCriterion("AccountId in", values, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotIn(List<Long> values) {
            addCriterion("AccountId not in", values, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidBetween(Long value1, Long value2) {
            addCriterion("AccountId between", value1, value2, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotBetween(Long value1, Long value2) {
            addCriterion("AccountId not between", value1, value2, "accountid");
            return (Criteria) this;
        }

        public Criteria andPositionidIsNull() {
            addCriterion("PositionId is null");
            return (Criteria) this;
        }

        public Criteria andPositionidIsNotNull() {
            addCriterion("PositionId is not null");
            return (Criteria) this;
        }

        public Criteria andPositionidEqualTo(Long value) {
            addCriterion("PositionId =", value, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidNotEqualTo(Long value) {
            addCriterion("PositionId <>", value, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidGreaterThan(Long value) {
            addCriterion("PositionId >", value, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidGreaterThanOrEqualTo(Long value) {
            addCriterion("PositionId >=", value, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidLessThan(Long value) {
            addCriterion("PositionId <", value, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidLessThanOrEqualTo(Long value) {
            addCriterion("PositionId <=", value, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidIn(List<Long> values) {
            addCriterion("PositionId in", values, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidNotIn(List<Long> values) {
            addCriterion("PositionId not in", values, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidBetween(Long value1, Long value2) {
            addCriterion("PositionId between", value1, value2, "positionid");
            return (Criteria) this;
        }

        public Criteria andPositionidNotBetween(Long value1, Long value2) {
            addCriterion("PositionId not between", value1, value2, "positionid");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeIsNull() {
            addCriterion("BeginVolume is null");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeIsNotNull() {
            addCriterion("BeginVolume is not null");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeEqualTo(Double value) {
            addCriterion("BeginVolume =", value, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeNotEqualTo(Double value) {
            addCriterion("BeginVolume <>", value, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeGreaterThan(Double value) {
            addCriterion("BeginVolume >", value, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("BeginVolume >=", value, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeLessThan(Double value) {
            addCriterion("BeginVolume <", value, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeLessThanOrEqualTo(Double value) {
            addCriterion("BeginVolume <=", value, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeIn(List<Double> values) {
            addCriterion("BeginVolume in", values, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeNotIn(List<Double> values) {
            addCriterion("BeginVolume not in", values, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeBetween(Double value1, Double value2) {
            addCriterion("BeginVolume between", value1, value2, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andBeginvolumeNotBetween(Double value1, Double value2) {
            addCriterion("BeginVolume not between", value1, value2, "beginvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeIsNull() {
            addCriterion("EndVolume is null");
            return (Criteria) this;
        }

        public Criteria andEndvolumeIsNotNull() {
            addCriterion("EndVolume is not null");
            return (Criteria) this;
        }

        public Criteria andEndvolumeEqualTo(Double value) {
            addCriterion("EndVolume =", value, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeNotEqualTo(Double value) {
            addCriterion("EndVolume <>", value, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeGreaterThan(Double value) {
            addCriterion("EndVolume >", value, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("EndVolume >=", value, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeLessThan(Double value) {
            addCriterion("EndVolume <", value, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeLessThanOrEqualTo(Double value) {
            addCriterion("EndVolume <=", value, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeIn(List<Double> values) {
            addCriterion("EndVolume in", values, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeNotIn(List<Double> values) {
            addCriterion("EndVolume not in", values, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeBetween(Double value1, Double value2) {
            addCriterion("EndVolume between", value1, value2, "endvolume");
            return (Criteria) this;
        }

        public Criteria andEndvolumeNotBetween(Double value1, Double value2) {
            addCriterion("EndVolume not between", value1, value2, "endvolume");
            return (Criteria) this;
        }

        public Criteria andBillamountIsNull() {
            addCriterion("BillAmount is null");
            return (Criteria) this;
        }

        public Criteria andBillamountIsNotNull() {
            addCriterion("BillAmount is not null");
            return (Criteria) this;
        }

        public Criteria andBillamountEqualTo(Long value) {
            addCriterion("BillAmount =", value, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountNotEqualTo(Long value) {
            addCriterion("BillAmount <>", value, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountGreaterThan(Long value) {
            addCriterion("BillAmount >", value, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountGreaterThanOrEqualTo(Long value) {
            addCriterion("BillAmount >=", value, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountLessThan(Long value) {
            addCriterion("BillAmount <", value, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountLessThanOrEqualTo(Long value) {
            addCriterion("BillAmount <=", value, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountIn(List<Long> values) {
            addCriterion("BillAmount in", values, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountNotIn(List<Long> values) {
            addCriterion("BillAmount not in", values, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountBetween(Long value1, Long value2) {
            addCriterion("BillAmount between", value1, value2, "billamount");
            return (Criteria) this;
        }

        public Criteria andBillamountNotBetween(Long value1, Long value2) {
            addCriterion("BillAmount not between", value1, value2, "billamount");
            return (Criteria) this;
        }

        public Criteria andYearmonthIsNull() {
            addCriterion("YearMonth is null");
            return (Criteria) this;
        }

        public Criteria andYearmonthIsNotNull() {
            addCriterion("YearMonth is not null");
            return (Criteria) this;
        }

        public Criteria andYearmonthEqualTo(String value) {
            addCriterion("YearMonth =", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthNotEqualTo(String value) {
            addCriterion("YearMonth <>", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthGreaterThan(String value) {
            addCriterion("YearMonth >", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthGreaterThanOrEqualTo(String value) {
            addCriterion("YearMonth >=", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthLessThan(String value) {
            addCriterion("YearMonth <", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthLessThanOrEqualTo(String value) {
            addCriterion("YearMonth <=", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthLike(String value) {
            addCriterion("YearMonth like", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthNotLike(String value) {
            addCriterion("YearMonth not like", value, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthIn(List<String> values) {
            addCriterion("YearMonth in", values, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthNotIn(List<String> values) {
            addCriterion("YearMonth not in", values, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthBetween(String value1, String value2) {
            addCriterion("YearMonth between", value1, value2, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andYearmonthNotBetween(String value1, String value2) {
            addCriterion("YearMonth not between", value1, value2, "yearmonth");
            return (Criteria) this;
        }

        public Criteria andSettlementdateIsNull() {
            addCriterion("SettlementDate is null");
            return (Criteria) this;
        }

        public Criteria andSettlementdateIsNotNull() {
            addCriterion("SettlementDate is not null");
            return (Criteria) this;
        }

        public Criteria andSettlementdateEqualTo(Date value) {
            addCriterion("SettlementDate =", value, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateNotEqualTo(Date value) {
            addCriterion("SettlementDate <>", value, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateGreaterThan(Date value) {
            addCriterion("SettlementDate >", value, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateGreaterThanOrEqualTo(Date value) {
            addCriterion("SettlementDate >=", value, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateLessThan(Date value) {
            addCriterion("SettlementDate <", value, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateLessThanOrEqualTo(Date value) {
            addCriterion("SettlementDate <=", value, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateIn(List<Date> values) {
            addCriterion("SettlementDate in", values, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateNotIn(List<Date> values) {
            addCriterion("SettlementDate not in", values, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateBetween(Date value1, Date value2) {
            addCriterion("SettlementDate between", value1, value2, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andSettlementdateNotBetween(Date value1, Date value2) {
            addCriterion("SettlementDate not between", value1, value2, "settlementdate");
            return (Criteria) this;
        }

        public Criteria andBegindateIsNull() {
            addCriterion("BeginDate is null");
            return (Criteria) this;
        }

        public Criteria andBegindateIsNotNull() {
            addCriterion("BeginDate is not null");
            return (Criteria) this;
        }

        public Criteria andBegindateEqualTo(Date value) {
            addCriterion("BeginDate =", value, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateNotEqualTo(Date value) {
            addCriterion("BeginDate <>", value, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateGreaterThan(Date value) {
            addCriterion("BeginDate >", value, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateGreaterThanOrEqualTo(Date value) {
            addCriterion("BeginDate >=", value, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateLessThan(Date value) {
            addCriterion("BeginDate <", value, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateLessThanOrEqualTo(Date value) {
            addCriterion("BeginDate <=", value, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateIn(List<Date> values) {
            addCriterion("BeginDate in", values, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateNotIn(List<Date> values) {
            addCriterion("BeginDate not in", values, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateBetween(Date value1, Date value2) {
            addCriterion("BeginDate between", value1, value2, "begindate");
            return (Criteria) this;
        }

        public Criteria andBegindateNotBetween(Date value1, Date value2) {
            addCriterion("BeginDate not between", value1, value2, "begindate");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNull() {
            addCriterion("EndDate is null");
            return (Criteria) this;
        }

        public Criteria andEnddateIsNotNull() {
            addCriterion("EndDate is not null");
            return (Criteria) this;
        }

        public Criteria andEnddateEqualTo(Date value) {
            addCriterion("EndDate =", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotEqualTo(Date value) {
            addCriterion("EndDate <>", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThan(Date value) {
            addCriterion("EndDate >", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateGreaterThanOrEqualTo(Date value) {
            addCriterion("EndDate >=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThan(Date value) {
            addCriterion("EndDate <", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateLessThanOrEqualTo(Date value) {
            addCriterion("EndDate <=", value, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateIn(List<Date> values) {
            addCriterion("EndDate in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotIn(List<Date> values) {
            addCriterion("EndDate not in", values, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateBetween(Date value1, Date value2) {
            addCriterion("EndDate between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andEnddateNotBetween(Date value1, Date value2) {
            addCriterion("EndDate not between", value1, value2, "enddate");
            return (Criteria) this;
        }

        public Criteria andStatusflagIsNull() {
            addCriterion("StatusFlag is null");
            return (Criteria) this;
        }

        public Criteria andStatusflagIsNotNull() {
            addCriterion("StatusFlag is not null");
            return (Criteria) this;
        }

        public Criteria andStatusflagEqualTo(Long value) {
            addCriterion("StatusFlag =", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagNotEqualTo(Long value) {
            addCriterion("StatusFlag <>", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagGreaterThan(Long value) {
            addCriterion("StatusFlag >", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagGreaterThanOrEqualTo(Long value) {
            addCriterion("StatusFlag >=", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagLessThan(Long value) {
            addCriterion("StatusFlag <", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagLessThanOrEqualTo(Long value) {
            addCriterion("StatusFlag <=", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagIn(List<Long> values) {
            addCriterion("StatusFlag in", values, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagNotIn(List<Long> values) {
            addCriterion("StatusFlag not in", values, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagBetween(Long value1, Long value2) {
            addCriterion("StatusFlag between", value1, value2, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagNotBetween(Long value1, Long value2) {
            addCriterion("StatusFlag not between", value1, value2, "statusflag");
            return (Criteria) this;
        }

        public Criteria andOverdueamountIsNull() {
            addCriterion("OverdueAmount is null");
            return (Criteria) this;
        }

        public Criteria andOverdueamountIsNotNull() {
            addCriterion("OverdueAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOverdueamountEqualTo(Long value) {
            addCriterion("OverdueAmount =", value, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountNotEqualTo(Long value) {
            addCriterion("OverdueAmount <>", value, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountGreaterThan(Long value) {
            addCriterion("OverdueAmount >", value, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountGreaterThanOrEqualTo(Long value) {
            addCriterion("OverdueAmount >=", value, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountLessThan(Long value) {
            addCriterion("OverdueAmount <", value, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountLessThanOrEqualTo(Long value) {
            addCriterion("OverdueAmount <=", value, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountIn(List<Long> values) {
            addCriterion("OverdueAmount in", values, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountNotIn(List<Long> values) {
            addCriterion("OverdueAmount not in", values, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountBetween(Long value1, Long value2) {
            addCriterion("OverdueAmount between", value1, value2, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andOverdueamountNotBetween(Long value1, Long value2) {
            addCriterion("OverdueAmount not between", value1, value2, "overdueamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountIsNull() {
            addCriterion("ShouldAmount is null");
            return (Criteria) this;
        }

        public Criteria andShouldamountIsNotNull() {
            addCriterion("ShouldAmount is not null");
            return (Criteria) this;
        }

        public Criteria andShouldamountEqualTo(Long value) {
            addCriterion("ShouldAmount =", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotEqualTo(Long value) {
            addCriterion("ShouldAmount <>", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountGreaterThan(Long value) {
            addCriterion("ShouldAmount >", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountGreaterThanOrEqualTo(Long value) {
            addCriterion("ShouldAmount >=", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountLessThan(Long value) {
            addCriterion("ShouldAmount <", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountLessThanOrEqualTo(Long value) {
            addCriterion("ShouldAmount <=", value, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountIn(List<Long> values) {
            addCriterion("ShouldAmount in", values, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotIn(List<Long> values) {
            addCriterion("ShouldAmount not in", values, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountBetween(Long value1, Long value2) {
            addCriterion("ShouldAmount between", value1, value2, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andShouldamountNotBetween(Long value1, Long value2) {
            addCriterion("ShouldAmount not between", value1, value2, "shouldamount");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNull() {
            addCriterion("PayTime is null");
            return (Criteria) this;
        }

        public Criteria andPaytimeIsNotNull() {
            addCriterion("PayTime is not null");
            return (Criteria) this;
        }

        public Criteria andPaytimeEqualTo(Date value) {
            addCriterion("PayTime =", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotEqualTo(Date value) {
            addCriterion("PayTime <>", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThan(Date value) {
            addCriterion("PayTime >", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("PayTime >=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThan(Date value) {
            addCriterion("PayTime <", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeLessThanOrEqualTo(Date value) {
            addCriterion("PayTime <=", value, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeIn(List<Date> values) {
            addCriterion("PayTime in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotIn(List<Date> values) {
            addCriterion("PayTime not in", values, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeBetween(Date value1, Date value2) {
            addCriterion("PayTime between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andPaytimeNotBetween(Date value1, Date value2) {
            addCriterion("PayTime not between", value1, value2, "paytime");
            return (Criteria) this;
        }

        public Criteria andActualamountIsNull() {
            addCriterion("ActualAmount is null");
            return (Criteria) this;
        }

        public Criteria andActualamountIsNotNull() {
            addCriterion("ActualAmount is not null");
            return (Criteria) this;
        }

        public Criteria andActualamountEqualTo(Long value) {
            addCriterion("ActualAmount =", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotEqualTo(Long value) {
            addCriterion("ActualAmount <>", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountGreaterThan(Long value) {
            addCriterion("ActualAmount >", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountGreaterThanOrEqualTo(Long value) {
            addCriterion("ActualAmount >=", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountLessThan(Long value) {
            addCriterion("ActualAmount <", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountLessThanOrEqualTo(Long value) {
            addCriterion("ActualAmount <=", value, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountIn(List<Long> values) {
            addCriterion("ActualAmount in", values, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotIn(List<Long> values) {
            addCriterion("ActualAmount not in", values, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountBetween(Long value1, Long value2) {
            addCriterion("ActualAmount between", value1, value2, "actualamount");
            return (Criteria) this;
        }

        public Criteria andActualamountNotBetween(Long value1, Long value2) {
            addCriterion("ActualAmount not between", value1, value2, "actualamount");
            return (Criteria) this;
        }

        public Criteria andWateramountIsNull() {
            addCriterion("WaterAmount is null");
            return (Criteria) this;
        }

        public Criteria andWateramountIsNotNull() {
            addCriterion("WaterAmount is not null");
            return (Criteria) this;
        }

        public Criteria andWateramountEqualTo(Long value) {
            addCriterion("WaterAmount =", value, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountNotEqualTo(Long value) {
            addCriterion("WaterAmount <>", value, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountGreaterThan(Long value) {
            addCriterion("WaterAmount >", value, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountGreaterThanOrEqualTo(Long value) {
            addCriterion("WaterAmount >=", value, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountLessThan(Long value) {
            addCriterion("WaterAmount <", value, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountLessThanOrEqualTo(Long value) {
            addCriterion("WaterAmount <=", value, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountIn(List<Long> values) {
            addCriterion("WaterAmount in", values, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountNotIn(List<Long> values) {
            addCriterion("WaterAmount not in", values, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountBetween(Long value1, Long value2) {
            addCriterion("WaterAmount between", value1, value2, "wateramount");
            return (Criteria) this;
        }

        public Criteria andWateramountNotBetween(Long value1, Long value2) {
            addCriterion("WaterAmount not between", value1, value2, "wateramount");
            return (Criteria) this;
        }

        public Criteria andSewageamountIsNull() {
            addCriterion("SewageAmount is null");
            return (Criteria) this;
        }

        public Criteria andSewageamountIsNotNull() {
            addCriterion("SewageAmount is not null");
            return (Criteria) this;
        }

        public Criteria andSewageamountEqualTo(Long value) {
            addCriterion("SewageAmount =", value, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountNotEqualTo(Long value) {
            addCriterion("SewageAmount <>", value, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountGreaterThan(Long value) {
            addCriterion("SewageAmount >", value, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountGreaterThanOrEqualTo(Long value) {
            addCriterion("SewageAmount >=", value, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountLessThan(Long value) {
            addCriterion("SewageAmount <", value, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountLessThanOrEqualTo(Long value) {
            addCriterion("SewageAmount <=", value, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountIn(List<Long> values) {
            addCriterion("SewageAmount in", values, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountNotIn(List<Long> values) {
            addCriterion("SewageAmount not in", values, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountBetween(Long value1, Long value2) {
            addCriterion("SewageAmount between", value1, value2, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andSewageamountNotBetween(Long value1, Long value2) {
            addCriterion("SewageAmount not between", value1, value2, "sewageamount");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateIsNull() {
            addCriterion("LastPayCostDate is null");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateIsNotNull() {
            addCriterion("LastPayCostDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateEqualTo(Date value) {
            addCriterion("LastPayCostDate =", value, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateNotEqualTo(Date value) {
            addCriterion("LastPayCostDate <>", value, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateGreaterThan(Date value) {
            addCriterion("LastPayCostDate >", value, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateGreaterThanOrEqualTo(Date value) {
            addCriterion("LastPayCostDate >=", value, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateLessThan(Date value) {
            addCriterion("LastPayCostDate <", value, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateLessThanOrEqualTo(Date value) {
            addCriterion("LastPayCostDate <=", value, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateIn(List<Date> values) {
            addCriterion("LastPayCostDate in", values, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateNotIn(List<Date> values) {
            addCriterion("LastPayCostDate not in", values, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateBetween(Date value1, Date value2) {
            addCriterion("LastPayCostDate between", value1, value2, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andLastpaycostdateNotBetween(Date value1, Date value2) {
            addCriterion("LastPayCostDate not between", value1, value2, "lastpaycostdate");
            return (Criteria) this;
        }

        public Criteria andOtheramountIsNull() {
            addCriterion("OtherAmount is null");
            return (Criteria) this;
        }

        public Criteria andOtheramountIsNotNull() {
            addCriterion("OtherAmount is not null");
            return (Criteria) this;
        }

        public Criteria andOtheramountEqualTo(Long value) {
            addCriterion("OtherAmount =", value, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountNotEqualTo(Long value) {
            addCriterion("OtherAmount <>", value, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountGreaterThan(Long value) {
            addCriterion("OtherAmount >", value, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountGreaterThanOrEqualTo(Long value) {
            addCriterion("OtherAmount >=", value, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountLessThan(Long value) {
            addCriterion("OtherAmount <", value, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountLessThanOrEqualTo(Long value) {
            addCriterion("OtherAmount <=", value, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountIn(List<Long> values) {
            addCriterion("OtherAmount in", values, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountNotIn(List<Long> values) {
            addCriterion("OtherAmount not in", values, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountBetween(Long value1, Long value2) {
            addCriterion("OtherAmount between", value1, value2, "otheramount");
            return (Criteria) this;
        }

        public Criteria andOtheramountNotBetween(Long value1, Long value2) {
            addCriterion("OtherAmount not between", value1, value2, "otheramount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AccountBill
     *
     * @mbggenerated do_not_delete_during_merge Fri May 01 19:39:36 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table AccountBill
     *
     * @mbggenerated Fri May 01 19:39:36 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}