package com.lion.controllerability.basisposition.mapper;

import com.lion.controllerability.basisposition.data.Basisposition;
import com.lion.controllerability.basisposition.data.BasispositionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BasispositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int countByExample(BasispositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int deleteByExample(BasispositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int deleteByPrimaryKey(Long positionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int insert(Basisposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int insertSelective(Basisposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    List<Basisposition> selectByExample(BasispositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    Basisposition selectByPrimaryKey(Long positionid);

    Basisposition selectByPositionName(String positionname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Basisposition record, @Param("example") BasispositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int updateByExample(@Param("record") Basisposition record, @Param("example") BasispositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int updateByPrimaryKeySelective(Basisposition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Basisposition
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    int updateByPrimaryKey(Basisposition record);

    Basisposition getByPositionId(Long positionId);
}