package com.lion.controllerability.accountMeter.mapper;

import com.lion.controllerability.accountMeter.data.Accountmeter;
import com.lion.controllerability.accountMeter.data.AccountmeterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountmeterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int countByExample(AccountmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int deleteByExample(AccountmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int insert(Accountmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int insertSelective(Accountmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    List<Accountmeter> selectByExample(AccountmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    Accountmeter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int updateByExampleSelective(@Param("record") Accountmeter record, @Param("example") AccountmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int updateByExample(@Param("record") Accountmeter record, @Param("example") AccountmeterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int updateByPrimaryKeySelective(Accountmeter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountMeter
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    int updateByPrimaryKey(Accountmeter record);
}