package com.lion.controllerability.basisposition.data;

public class Basisposition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.PositionId
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private Long positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.DistrictCode
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private String districtcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.ParentId
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.PositionNo
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private String positionno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.PositionName
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private String positionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.EstateBriefName
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private String estatebriefname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.EstateAddress
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private String estateaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.TypeFlag
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private Byte typeflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Basisposition.ActiveFlag
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    private Byte activeflag;

    private Integer count ;

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.PositionId
     *
     * @return the value of Basisposition.PositionId
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public Long getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.PositionId
     *
     * @param positionid the value for Basisposition.PositionId
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setPositionid(Long positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.DistrictCode
     *
     * @return the value of Basisposition.DistrictCode
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public String getDistrictcode() {
        return districtcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.DistrictCode
     *
     * @param districtcode the value for Basisposition.DistrictCode
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setDistrictcode(String districtcode) {
        this.districtcode = districtcode == null ? null : districtcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.ParentId
     *
     * @return the value of Basisposition.ParentId
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.ParentId
     *
     * @param parentid the value for Basisposition.ParentId
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.PositionNo
     *
     * @return the value of Basisposition.PositionNo
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public String getPositionno() {
        return positionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.PositionNo
     *
     * @param positionno the value for Basisposition.PositionNo
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setPositionno(String positionno) {
        this.positionno = positionno == null ? null : positionno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.PositionName
     *
     * @return the value of Basisposition.PositionName
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public String getPositionname() {
        return positionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.PositionName
     *
     * @param positionname the value for Basisposition.PositionName
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setPositionname(String positionname) {
        this.positionname = positionname == null ? null : positionname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.EstateBriefName
     *
     * @return the value of Basisposition.EstateBriefName
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public String getEstatebriefname() {
        return estatebriefname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.EstateBriefName
     *
     * @param estatebriefname the value for Basisposition.EstateBriefName
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setEstatebriefname(String estatebriefname) {
        this.estatebriefname = estatebriefname == null ? null : estatebriefname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.EstateAddress
     *
     * @return the value of Basisposition.EstateAddress
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public String getEstateaddress() {
        return estateaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.EstateAddress
     *
     * @param estateaddress the value for Basisposition.EstateAddress
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setEstateaddress(String estateaddress) {
        this.estateaddress = estateaddress == null ? null : estateaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.TypeFlag
     *
     * @return the value of Basisposition.TypeFlag
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public Byte getTypeflag() {
        return typeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.TypeFlag
     *
     * @param typeflag the value for Basisposition.TypeFlag
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setTypeflag(Byte typeflag) {
        this.typeflag = typeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Basisposition.ActiveFlag
     *
     * @return the value of Basisposition.ActiveFlag
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public Byte getActiveflag() {
        return activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Basisposition.ActiveFlag
     *
     * @param activeflag the value for Basisposition.ActiveFlag
     *
     * @mbggenerated Tue Mar 03 20:50:18 CST 2020
     */
    public void setActiveflag(Byte activeflag) {
        this.activeflag = activeflag;
    }
}