package com.lion.controllerability.accountBase.mapper;

import com.lion.controllerability.accountBase.data.Accountbase;
import com.lion.controllerability.accountBase.data.AccountbaseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;

@Mapper
public interface AccountbaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int countByExample(AccountbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int deleteByExample(AccountbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int deleteByPrimaryKey(Long accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int insert(Accountbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int insertSelective(Accountbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    List<Accountbase> selectByExample(AccountbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    Accountbase selectByPrimaryKey(Long accountid);

    Accountbase selectByPosionId(Long posionId);

    Accountbase selectByCustomerId(Long CustomerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") Accountbase record, @Param("example") AccountbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int updateByExample(@Param("record") Accountbase record, @Param("example") AccountbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int updateByPrimaryKeySelective(Accountbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AccountBase
     *
     * @mbggenerated Sun Mar 08 10:33:11 CST 2020
     */
    int updateByPrimaryKey(Accountbase record);
}