package com.lion.controllerability.accountMeter.data;

import java.util.Date;

public class Accountmeter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountMeter.Id
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountMeter.AccountId
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    private Long accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountMeter.MeterId
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    private Long meterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountMeter.BindTime
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    private Date bindtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountMeter.BeginDigit
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    private Double begindigit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AccountMeter.ActiveFlag
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    private Byte activeflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountMeter.Id
     *
     * @return the value of AccountMeter.Id
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountMeter.Id
     *
     * @param id the value for AccountMeter.Id
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountMeter.AccountId
     *
     * @return the value of AccountMeter.AccountId
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public Long getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountMeter.AccountId
     *
     * @param accountid the value for AccountMeter.AccountId
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public void setAccountid(Long accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountMeter.MeterId
     *
     * @return the value of AccountMeter.MeterId
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public Long getMeterid() {
        return meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountMeter.MeterId
     *
     * @param meterid the value for AccountMeter.MeterId
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public void setMeterid(Long meterid) {
        this.meterid = meterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountMeter.BindTime
     *
     * @return the value of AccountMeter.BindTime
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public Date getBindtime() {
        return bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountMeter.BindTime
     *
     * @param bindtime the value for AccountMeter.BindTime
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public void setBindtime(Date bindtime) {
        this.bindtime = bindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountMeter.BeginDigit
     *
     * @return the value of AccountMeter.BeginDigit
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public Double getBegindigit() {
        return begindigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountMeter.BeginDigit
     *
     * @param begindigit the value for AccountMeter.BeginDigit
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public void setBegindigit(Double begindigit) {
        this.begindigit = begindigit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AccountMeter.ActiveFlag
     *
     * @return the value of AccountMeter.ActiveFlag
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public Byte getActiveflag() {
        return activeflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AccountMeter.ActiveFlag
     *
     * @param activeflag the value for AccountMeter.ActiveFlag
     *
     * @mbggenerated Wed Mar 18 12:27:57 CST 2020
     */
    public void setActiveflag(Byte activeflag) {
        this.activeflag = activeflag;
    }
}