package com.lion.controllerability.meterBase.data;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MeterbaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public MeterbaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMeteridIsNull() {
            addCriterion("MeterId is null");
            return (Criteria) this;
        }

        public Criteria andMeteridIsNotNull() {
            addCriterion("MeterId is not null");
            return (Criteria) this;
        }

        public Criteria andMeteridEqualTo(Long value) {
            addCriterion("MeterId =", value, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridNotEqualTo(Long value) {
            addCriterion("MeterId <>", value, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridGreaterThan(Long value) {
            addCriterion("MeterId >", value, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridGreaterThanOrEqualTo(Long value) {
            addCriterion("MeterId >=", value, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridLessThan(Long value) {
            addCriterion("MeterId <", value, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridLessThanOrEqualTo(Long value) {
            addCriterion("MeterId <=", value, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridIn(List<Long> values) {
            addCriterion("MeterId in", values, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridNotIn(List<Long> values) {
            addCriterion("MeterId not in", values, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridBetween(Long value1, Long value2) {
            addCriterion("MeterId between", value1, value2, "meterid");
            return (Criteria) this;
        }

        public Criteria andMeteridNotBetween(Long value1, Long value2) {
            addCriterion("MeterId not between", value1, value2, "meterid");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNull() {
            addCriterion("TypeId is null");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNotNull() {
            addCriterion("TypeId is not null");
            return (Criteria) this;
        }

        public Criteria andTypeidEqualTo(String value) {
            addCriterion("TypeId =", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotEqualTo(String value) {
            addCriterion("TypeId <>", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThan(String value) {
            addCriterion("TypeId >", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThanOrEqualTo(String value) {
            addCriterion("TypeId >=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThan(String value) {
            addCriterion("TypeId <", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThanOrEqualTo(String value) {
            addCriterion("TypeId <=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLike(String value) {
            addCriterion("TypeId like", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotLike(String value) {
            addCriterion("TypeId not like", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidIn(List<String> values) {
            addCriterion("TypeId in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotIn(List<String> values) {
            addCriterion("TypeId not in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidBetween(String value1, String value2) {
            addCriterion("TypeId between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotBetween(String value1, String value2) {
            addCriterion("TypeId not between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andMeternoIsNull() {
            addCriterion("MeterNo is null");
            return (Criteria) this;
        }

        public Criteria andMeternoIsNotNull() {
            addCriterion("MeterNo is not null");
            return (Criteria) this;
        }

        public Criteria andMeternoEqualTo(String value) {
            addCriterion("MeterNo =", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoNotEqualTo(String value) {
            addCriterion("MeterNo <>", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoGreaterThan(String value) {
            addCriterion("MeterNo >", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoGreaterThanOrEqualTo(String value) {
            addCriterion("MeterNo >=", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoLessThan(String value) {
            addCriterion("MeterNo <", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoLessThanOrEqualTo(String value) {
            addCriterion("MeterNo <=", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoLike(String value) {
            addCriterion("MeterNo like", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoNotLike(String value) {
            addCriterion("MeterNo not like", value, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoIn(List<String> values) {
            addCriterion("MeterNo in", values, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoNotIn(List<String> values) {
            addCriterion("MeterNo not in", values, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoBetween(String value1, String value2) {
            addCriterion("MeterNo between", value1, value2, "meterno");
            return (Criteria) this;
        }

        public Criteria andMeternoNotBetween(String value1, String value2) {
            addCriterion("MeterNo not between", value1, value2, "meterno");
            return (Criteria) this;
        }

        public Criteria andImeiIsNull() {
            addCriterion("Imei is null");
            return (Criteria) this;
        }

        public Criteria andImeiIsNotNull() {
            addCriterion("Imei is not null");
            return (Criteria) this;
        }

        public Criteria andImeiEqualTo(String value) {
            addCriterion("Imei =", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotEqualTo(String value) {
            addCriterion("Imei <>", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThan(String value) {
            addCriterion("Imei >", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiGreaterThanOrEqualTo(String value) {
            addCriterion("Imei >=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThan(String value) {
            addCriterion("Imei <", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLessThanOrEqualTo(String value) {
            addCriterion("Imei <=", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiLike(String value) {
            addCriterion("Imei like", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotLike(String value) {
            addCriterion("Imei not like", value, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiIn(List<String> values) {
            addCriterion("Imei in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotIn(List<String> values) {
            addCriterion("Imei not in", values, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiBetween(String value1, String value2) {
            addCriterion("Imei between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andImeiNotBetween(String value1, String value2) {
            addCriterion("Imei not between", value1, value2, "imei");
            return (Criteria) this;
        }

        public Criteria andImsiIsNull() {
            addCriterion("Imsi is null");
            return (Criteria) this;
        }

        public Criteria andImsiIsNotNull() {
            addCriterion("Imsi is not null");
            return (Criteria) this;
        }

        public Criteria andImsiEqualTo(String value) {
            addCriterion("Imsi =", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotEqualTo(String value) {
            addCriterion("Imsi <>", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiGreaterThan(String value) {
            addCriterion("Imsi >", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiGreaterThanOrEqualTo(String value) {
            addCriterion("Imsi >=", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiLessThan(String value) {
            addCriterion("Imsi <", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiLessThanOrEqualTo(String value) {
            addCriterion("Imsi <=", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiLike(String value) {
            addCriterion("Imsi like", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotLike(String value) {
            addCriterion("Imsi not like", value, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiIn(List<String> values) {
            addCriterion("Imsi in", values, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotIn(List<String> values) {
            addCriterion("Imsi not in", values, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiBetween(String value1, String value2) {
            addCriterion("Imsi between", value1, value2, "imsi");
            return (Criteria) this;
        }

        public Criteria andImsiNotBetween(String value1, String value2) {
            addCriterion("Imsi not between", value1, value2, "imsi");
            return (Criteria) this;
        }

        public Criteria andStatusflagIsNull() {
            addCriterion("StatusFlag is null");
            return (Criteria) this;
        }

        public Criteria andStatusflagIsNotNull() {
            addCriterion("StatusFlag is not null");
            return (Criteria) this;
        }

        public Criteria andStatusflagEqualTo(Byte value) {
            addCriterion("StatusFlag =", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagNotEqualTo(Byte value) {
            addCriterion("StatusFlag <>", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagGreaterThan(Byte value) {
            addCriterion("StatusFlag >", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagGreaterThanOrEqualTo(Byte value) {
            addCriterion("StatusFlag >=", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagLessThan(Byte value) {
            addCriterion("StatusFlag <", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagLessThanOrEqualTo(Byte value) {
            addCriterion("StatusFlag <=", value, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagIn(List<Byte> values) {
            addCriterion("StatusFlag in", values, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagNotIn(List<Byte> values) {
            addCriterion("StatusFlag not in", values, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagBetween(Byte value1, Byte value2) {
            addCriterion("StatusFlag between", value1, value2, "statusflag");
            return (Criteria) this;
        }

        public Criteria andStatusflagNotBetween(Byte value1, Byte value2) {
            addCriterion("StatusFlag not between", value1, value2, "statusflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagIsNull() {
            addCriterion("SyncFlag is null");
            return (Criteria) this;
        }

        public Criteria andSyncflagIsNotNull() {
            addCriterion("SyncFlag is not null");
            return (Criteria) this;
        }

        public Criteria andSyncflagEqualTo(Byte value) {
            addCriterion("SyncFlag =", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotEqualTo(Byte value) {
            addCriterion("SyncFlag <>", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagGreaterThan(Byte value) {
            addCriterion("SyncFlag >", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagGreaterThanOrEqualTo(Byte value) {
            addCriterion("SyncFlag >=", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagLessThan(Byte value) {
            addCriterion("SyncFlag <", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagLessThanOrEqualTo(Byte value) {
            addCriterion("SyncFlag <=", value, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagIn(List<Byte> values) {
            addCriterion("SyncFlag in", values, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotIn(List<Byte> values) {
            addCriterion("SyncFlag not in", values, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagBetween(Byte value1, Byte value2) {
            addCriterion("SyncFlag between", value1, value2, "syncflag");
            return (Criteria) this;
        }

        public Criteria andSyncflagNotBetween(Byte value1, Byte value2) {
            addCriterion("SyncFlag not between", value1, value2, "syncflag");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeIsNull() {
            addCriterion("LastCommuniationTime is null");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeIsNotNull() {
            addCriterion("LastCommuniationTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeEqualTo(Date value) {
            addCriterion("LastCommuniationTime =", value, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeNotEqualTo(Date value) {
            addCriterion("LastCommuniationTime <>", value, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeGreaterThan(Date value) {
            addCriterion("LastCommuniationTime >", value, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastCommuniationTime >=", value, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeLessThan(Date value) {
            addCriterion("LastCommuniationTime <", value, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeLessThanOrEqualTo(Date value) {
            addCriterion("LastCommuniationTime <=", value, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeIn(List<Date> values) {
            addCriterion("LastCommuniationTime in", values, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeNotIn(List<Date> values) {
            addCriterion("LastCommuniationTime not in", values, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeBetween(Date value1, Date value2) {
            addCriterion("LastCommuniationTime between", value1, value2, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andLastcommuniationtimeNotBetween(Date value1, Date value2) {
            addCriterion("LastCommuniationTime not between", value1, value2, "lastcommuniationtime");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNull() {
            addCriterion("Volume is null");
            return (Criteria) this;
        }

        public Criteria andVolumeIsNotNull() {
            addCriterion("Volume is not null");
            return (Criteria) this;
        }

        public Criteria andVolumeEqualTo(Double value) {
            addCriterion("Volume =", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotEqualTo(Double value) {
            addCriterion("Volume <>", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThan(Double value) {
            addCriterion("Volume >", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeGreaterThanOrEqualTo(Double value) {
            addCriterion("Volume >=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThan(Double value) {
            addCriterion("Volume <", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeLessThanOrEqualTo(Double value) {
            addCriterion("Volume <=", value, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeIn(List<Double> values) {
            addCriterion("Volume in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotIn(List<Double> values) {
            addCriterion("Volume not in", values, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeBetween(Double value1, Double value2) {
            addCriterion("Volume between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVolumeNotBetween(Double value1, Double value2) {
            addCriterion("Volume not between", value1, value2, "volume");
            return (Criteria) this;
        }

        public Criteria andVoltageIsNull() {
            addCriterion("Voltage is null");
            return (Criteria) this;
        }

        public Criteria andVoltageIsNotNull() {
            addCriterion("Voltage is not null");
            return (Criteria) this;
        }

        public Criteria andVoltageEqualTo(Double value) {
            addCriterion("Voltage =", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotEqualTo(Double value) {
            addCriterion("Voltage <>", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageGreaterThan(Double value) {
            addCriterion("Voltage >", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageGreaterThanOrEqualTo(Double value) {
            addCriterion("Voltage >=", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLessThan(Double value) {
            addCriterion("Voltage <", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageLessThanOrEqualTo(Double value) {
            addCriterion("Voltage <=", value, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageIn(List<Double> values) {
            addCriterion("Voltage in", values, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotIn(List<Double> values) {
            addCriterion("Voltage not in", values, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageBetween(Double value1, Double value2) {
            addCriterion("Voltage between", value1, value2, "voltage");
            return (Criteria) this;
        }

        public Criteria andVoltageNotBetween(Double value1, Double value2) {
            addCriterion("Voltage not between", value1, value2, "voltage");
            return (Criteria) this;
        }

        public Criteria andDeviceidIsNull() {
            addCriterion("DeviceId is null");
            return (Criteria) this;
        }

        public Criteria andDeviceidIsNotNull() {
            addCriterion("DeviceId is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceidEqualTo(String value) {
            addCriterion("DeviceId =", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotEqualTo(String value) {
            addCriterion("DeviceId <>", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidGreaterThan(String value) {
            addCriterion("DeviceId >", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidGreaterThanOrEqualTo(String value) {
            addCriterion("DeviceId >=", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidLessThan(String value) {
            addCriterion("DeviceId <", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidLessThanOrEqualTo(String value) {
            addCriterion("DeviceId <=", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidLike(String value) {
            addCriterion("DeviceId like", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotLike(String value) {
            addCriterion("DeviceId not like", value, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidIn(List<String> values) {
            addCriterion("DeviceId in", values, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotIn(List<String> values) {
            addCriterion("DeviceId not in", values, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidBetween(String value1, String value2) {
            addCriterion("DeviceId between", value1, value2, "deviceid");
            return (Criteria) this;
        }

        public Criteria andDeviceidNotBetween(String value1, String value2) {
            addCriterion("DeviceId not between", value1, value2, "deviceid");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeIsNull() {
            addCriterion("UseTypeCode is null");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeIsNotNull() {
            addCriterion("UseTypeCode is not null");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeEqualTo(String value) {
            addCriterion("UseTypeCode =", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeNotEqualTo(String value) {
            addCriterion("UseTypeCode <>", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeGreaterThan(String value) {
            addCriterion("UseTypeCode >", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeGreaterThanOrEqualTo(String value) {
            addCriterion("UseTypeCode >=", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeLessThan(String value) {
            addCriterion("UseTypeCode <", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeLessThanOrEqualTo(String value) {
            addCriterion("UseTypeCode <=", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeLike(String value) {
            addCriterion("UseTypeCode like", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeNotLike(String value) {
            addCriterion("UseTypeCode not like", value, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeIn(List<String> values) {
            addCriterion("UseTypeCode in", values, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeNotIn(List<String> values) {
            addCriterion("UseTypeCode not in", values, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeBetween(String value1, String value2) {
            addCriterion("UseTypeCode between", value1, value2, "usetypecode");
            return (Criteria) this;
        }

        public Criteria andUsetypecodeNotBetween(String value1, String value2) {
            addCriterion("UseTypeCode not between", value1, value2, "usetypecode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MeterBase
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 18 16:12:54 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}