package com.lion.controllerability.meterBase.mapper;

import com.lion.controllerability.meterBase.data.Meterbase;
import com.lion.controllerability.meterBase.data.MeterbaseExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MeterbaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int countByExample(MeterbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int deleteByExample(MeterbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int deleteByPrimaryKey(Long meterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int insert(Meterbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int insertSelective(Meterbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    List<Meterbase> selectByExample(MeterbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    Meterbase selectByPrimaryKey(Long meterid);
    Meterbase selectByImei(String imei);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") Meterbase record, @Param("example") MeterbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int updateByExample(@Param("record") Meterbase record, @Param("example") MeterbaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int updateByPrimaryKeySelective(Meterbase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MeterBase
     *
     * @mbggenerated Wed Mar 18 16:12:54 CST 2020
     */
    int updateByPrimaryKey(Meterbase record);
}